# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.rootswordpress.com:587
mail_admin: admin@rootswordpress.com
mail_hostname: rootswordpress.com
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
